Jdp220902 1
piotr-grosicki/project-jdp-2209-02 pull request #1
Opened 2022-08-21 15:34 UTC by s20308-pj

2022-08-21 15:47 UTC, piotr-kostka approved these changes

2022-08-21 16:05 UTC, piotr-grosicki requested changes

2022-08-21 16:05 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ResponseEntity<Void> getProducts() {
implementacja powinna zawierac dto zeby dalo sie przetestowac odpowiedzi w postmanie

2022-08-21 18:13 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ResponseEntity<Void> getProducts() {
- dodałem ProductDto
- group
- proprawiłem productController

2022-08-21 18:28 UTC, piotr-grosicki requested changes

2022-08-21 18:28 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private Group group;
dto nie powinno zawierac encji w sobie, w dto trzymamy albo id albo inne dto

2022-08-22 04:00 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private Group group;
poprawiłem

2022-08-22 07:03 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private GroupDto groupDto;
Ja bym całkiem to usunął i zostawił tylko name, description i price

2022-08-22 08:09 UTC, piotr-grosicki requested changes
konflikty

2022-08-22 10:24 UTC, krzysiekn111 approved these changes

2022-08-22 12:24 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private GroupDto groupDto;
no tak, ale w tym momencie pozbywamy się możliwości wyszukiwania produktów po grupach

2022-08-22 12:32 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private GroupDto groupDto;
jak będziemy robili encję i relację to dodamy :)

2022-08-22 12:39 UTC, piotr-grosicki requested changes
wciaz konflikty do rozwiazania

2022-08-22 13:16 UTC, piotr-grosicki requested changes

2022-08-22 13:16 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Groups.java
> +public class Groups {
encje nie powinny powstac w tym zadaniu

2022-08-22 14:58 UTC, piotr-grosicki requested changes

2022-08-22 14:58 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public List<GroupsDto> getGroups() {
dlaczego z GroupDto zmieniasz na GroupsDto? wydaje sie ze GroupDto juz istnieje w repozytorium, teraz beda dwa

2022-08-22 16:25 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public List<GroupsDto> getGroups() {
ponieważ na naszym schemacie ta encja istnieje pod nazwą groups - nie group
groupDto jest w złym pakiecie - powinna być w domain.dto - tam jest groupsDto 
groupDot jest do usuniecia

2022-08-22 18:24 UTC, piotr-grosicki requested changes
w repozytorium beda dwa group dto, trzeba usunac jedno z nich

2022-08-22 18:26 UTC, piotr-grosicki requested changes
+ nowe konflikty

2022-08-22 18:37 UTC, s20308-pj commented
> 

groupDto z pakietu domain do usunięcia, zostaje w pakiecie domain.dto

2022-08-23 05:43 UTC, piotr-grosicki commented
> > 
> 
> groupDto z pakietu domain do usunięcia, zostaje w pakiecie domain.dto

no to trzeba usunac juz w tym PR

2022-08-24 06:08 UTC, piotr-grosicki approved these changes

2022-08-24 06:09 UTC, merged