JDP220902-22 add: GroupMapper, GroupService,GlobalHttpErrorHandler, G…
piotr-grosicki/project-jdp-2209-02 pull request #14
Opened 2022-08-26 14:16 UTC by s20308-pj

2022-08-26 19:23 UTC, ptynek commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    }
Nie jestem pewny czy w konstruktorze jest potrzebne Group i List carts. Patrząc na przykład z modułu 17 to nie podaje się kolumn z relacjami.

2022-08-26 19:41 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    }
taki konstruktor i tak istnieje -> @AllArgsConstructor
ten ma za zadanie stworzenie obiektu bez przekazywania Id - bo ten ma się tworzyć sam -> @GeneratedValue

2022-08-26 23:35 UTC, arekgorka reviewed
Myślę, że takie testy niewiele nam dają, oprócz tego że nasza aplikacja sztucznie się buduje poprawnie :D Dalej nie mamy obowiązkowego pola ID i nie sprawdziliśmy działania encji. Oczywiście "sklep" się buduje i to jest miłe ;)

2022-08-27 20:30 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +    private Group group;
Tu zamiast Grupy trzeba by dać sam id grupy

2022-08-27 20:31 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                new ArrayList<>()
pusta lista raczej nie może być

2022-08-27 20:32 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                new ArrayList<>());
pusta lista raczej nie może być

2022-08-28 11:55 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                new ArrayList<>()
tworząc grupę nie dodajesz do niej produktów tylko później

2022-08-28 19:41 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                new ArrayList<>());
ja to widzę tak - tworząc obiekt Group dajemy pustą listę, później tworząc produkty dodajemy je do listy

2022-08-29 15:50 UTC, s20308-pj commented
GroupDto > zmieniłem na List<Product> products na List<Long>  productsId;
GroupMapper > mieniłem mapowanie na pobieranie Produktu po Id
ProductMapper > dodałem e mapToProduct dodawanie relacji między Group i Product
GroupTestSuite > usunąłem test deleteGroup (zgodnie z wytycznymi nie mamy takiego endpointa)
Repository > w Group i Product zmieniłem CrudRepository na JpaRepository

2022-08-29 19:15 UTC, ptynek commented
Z tym nowym commitem zepsuła się metoda create. Wcześniej jak rozmawialiśmy działała. Jedyny problem jaki był wcześniej to new ArrayList. Niestety nie może ona być tworzona, bo nawet przy metodzie PUT tworzy cały czas nową listę, zamiast wpychać ID jakiegoś produktu. Próbuję cały czas rozwiązać ten problem, ale już brak mi pomysłów.

2022-08-29 19:19 UTC, ptynek commented
GET i POST działa. Niestety nie działa metoda PUT. Po pierwsze w ogóle nie robi update name i description jak i również nie wrzuca productIdList. Nie mam już pomysłu jak można to naprawić, ale wydaje mi się, że może mieć to coś współnego z tworzoną nową listą, jeżeli chodzi o dokładanie IdProduct

2022-08-29 19:37 UTC, ptynek commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                new ArrayList<>());
https://snipboard.io/VQWqTi.jpg

Niestety ale nie może być pusta lista. Próbowałem rozwiązać ten problem ale brakuje mi już dzisiaj weny do tego.

2022-08-30 07:04 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.createGroup(groupMapper.mapToNewGroup(groupDto));
groupService.createGroup(groupMapper.mapToGroup(groupDto));

2022-08-30 07:04 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PutMapping(produces = MediaType.APPLICATION_JSON_VALUE)
a nie czasem consumes = ?

2022-08-30 10:30 UTC, arekgorka requested changes

2022-08-30 10:30 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            fetch = FetchType.EAGER,
nie wiem czy nie lepiej dać tutaj .LAZY (w zasadzie jest to wartość domyślna dla tej relacji, więc można by linijkę 25 po prostu usunąć). Nie potrzebujemy chyba pobierać relacji wszystkich produktów z wszystkimi istniejącymi wózkami. 
Zawsze możemy to sobie "dociągnąć" jak będzie trzeba.

2022-08-30 10:30 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Setter
Czemu usuwasz @Data? Ona zawiera w sobie przecież @Getter i @Setter

2022-08-30 10:30 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Group with this ID do not exist", HttpStatus.BAD_REQUEST);
Szczegół ale ja bym dał coś w stylu "Group with given ID doesn't exist".

2022-08-30 18:26 UTC, ptynek commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Setter
@arekgorka owszem, ale jeżeli zrobisz test przez debugger to wyświetla błąd metody toString. Będzie to działało, ale tutaj jest akurat taka kosmetyka. Nie jestem pewny czy może to jakoś wpłynąć na działanie aplikacji, tutaj musiałby się wypowiedzieć @piotr-grosicki

2022-08-31 10:51 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Setter
jasne, dobrze wiedzieć :)

2022-08-31 16:25 UTC, piotr-kostka commented
Sprawdzone w postmanie, wszystko działa poprawnie

2022-08-31 19:17 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            fetch = FetchType.EAGER,
Kaskady typu ALL przy usuwaniu koszyka wyrzucą nam usera i produkty, może lepiej MERGE?

2022-08-31 20:31 UTC, piotr-kostka approved these changes

2022-08-31 20:53 UTC, arekgorka approved these changes

2022-08-31 21:10 UTC, merged