JDP220902-21 ProductController - rzeczywista implementacja metod
piotr-grosicki/project-jdp-2209-02 pull request #19
Opened 2022-08-27 20:18 UTC by piotr-kostka

2022-08-28 18:17 UTC, arekgorka commented
rozwiązałem konflikty w Product, ProductRepository i GroupReposittory ale przestało się budować.

2022-08-28 18:38 UTC, arekgorka requested changes
Po rozwiązaniu konfliktów w Product, ProductRepository i GroupRepository aplikacja się nie buduje.

2022-08-28 19:24 UTC, arekgorka approved these changes

2022-08-29 17:51 UTC, ptynek commented
Co jest nie tak napisane. Metoda Post nie wchodzi i wyrzuca błąd 500. Gdzieś w mapperze jest błąd
https://snipboard.io/yO3L4n.jpg

https://snipboard.io/v9NCUS.jpg

2022-08-29 19:47 UTC, piotr-kostka commented
Poprawione:
https://snipboard.io/jvIxMR.jpg
https://snipboard.io/aoP4DI.jpg

2022-08-30 13:18 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +    }
Może warto by wyrzucić wyjątek ProductNotFoundException jeśli wpiszę się nieistniejące id? 
Z pomocą: 
if(productRepository.existById(productId)) {
     productRepository.deleteById(productId);
} else {
     throw new ProductNotFoundException
}

2022-08-30 13:37 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +    }
jest to jakaś myśl :) dorzucę to po pracy

2022-08-30 15:58 UTC, Merior94 approved these changes

2022-08-30 15:58 UTC, s20308-pj approved these changes

2022-08-30 15:59 UTC, merged