Jdp220902-25 UserController
piotr-grosicki/project-jdp-2209-02 pull request #24
Opened 2022-08-30 17:26 UTC by Merior94

Metody powinny działać poprawnie

2022-08-30 18:43 UTC, Merior94 commented
Poprawki

2022-08-30 18:50 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +@Setter
setter tutaj niepotrzebny

2022-08-30 18:50 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public User mapToUser(UserDto userDto){
ta metoda jest do zmiany

2022-08-30 18:50 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +        System.out.println(user);
linijki od 31 do 33 moim zdaniem zbędne

2022-08-30 18:50 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +        System.out.println("New user: " + user.getLogin() + " created.");
ten sout tez niepotrzebny

2022-08-30 18:50 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public UserDto createUserKey(Long userId) throws UserNotFoundException {
w tej metodzie souty bym wywalił, reszta fajna

2022-08-30 19:43 UTC, Merior94 reviewed
Dzięki za feedback, poprawię i wyczyszczę souty

2022-08-31 11:36 UTC, arekgorka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    void testUserSave(){
w tym teście tak naprawdę badasz dokładnie to samo 3 razy. Nie wiem czy raz nie wystarczy ;)

2022-08-31 11:36 UTC, arekgorka commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        user.setUserKey(null);
nie wiem czy to trochę nie na około, skoro możesz wszystkie parametry ustawić w new User( tutaj ). Bo tak to robisz bezparametrowy konstruktor gdzie na każdym polu masz null, a potem ustawiasz to pole jeszcze raz na null.

2022-08-31 16:43 UTC, Merior94 commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +    void testUserSave(){
Zgadzam się. Ten test skrócę, ale chciałem sprawdzić czy dodanie trzech użytkowników doda faktycznie trzech. Sprawdzę to innym testem i sprawdzę tylko ilość wpisów w bazie

2022-08-31 16:48 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>  @AllArgsConstructor
@AllArgsConstructor można wywalić

2022-08-31 16:48 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>      private UserService userService;
w linijce 25 wyjątek bym nazwał po prostu "UserExistsException"

2022-08-31 16:50 UTC, piotr-kostka commented
Dodatkowo:
- jest już katalog "exceptions" przerzuć twoje wyjątki z katalogu "exception" do tego drugiego
- w klasie User trzeba usunąć z linijek 19 i 20 (strategy = GenerationType.IDENTITY) i @NotNull

2022-08-31 18:36 UTC, Merior94 commented
> Dodatkowo:
> 
> * jest już katalog "exceptions" przerzuć twoje wyjątki z katalogu "exception" do tego drugiego
> * w klasie User trzeba usunąć z linijek 19 i 20 (strategy = GenerationType.IDENTITY) i @NotNull

W jakim celu usuwamy @NotNull ?

2022-08-31 18:52 UTC, Merior94 commented
Wprowadziłem sugestie. 
Nie mergujmy na razie bo poszło niestety z niedokończonym testem :x

2022-08-31 19:15 UTC, Merior94 commented
Usunięcie @NotNull z klasy User ||
Zmiana kaskady w klasie Cart - usunięcie koszyka powodowało usunięcie usera i produktów ||
Test pozostawienia usera po usunięciu Carta ||
Dodano metodę delete() w klasie UserRepository + wyczyszczenie kodu w klasach wykorzystujących usuwanie usera

2022-08-31 20:36 UTC, piotr-kostka commented
> > Dodatkowo:
> > 
> > * jest już katalog "exceptions" przerzuć twoje wyjątki z katalogu "exception" do tego drugiego
> > * w klasie User trzeba usunąć z linijek 19 i 20 (strategy = GenerationType.IDENTITY) i @NotNull
> 
> W jakim celu usuwamy @NotNull ?

Usuwamy bo wyskakują błędy a skoro mamy adnotację @Id i @GeneratedValue to to pole nigdy nie będzie puste

2022-08-31 21:09 UTC, piotr-kostka requested changes
Jak doda się "final" w UserControllerze to wszystko działa - sprawdzone w Postmanie

2022-08-31 21:09 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    private UserService userService;
tutaj tylko trzeba dodać "final" i działa :)

2022-08-31 21:12 UTC, piotr-kostka commented
no i konflikty trzeba poprawić po mergu GroupControllera :)

2022-09-01 15:23 UTC, piotr-kostka approved these changes

2022-09-01 15:50 UTC, arekgorka approved these changes

2022-09-01 16:38 UTC, merged