Jdp220902 23
piotr-grosicki/project-jdp-2209-02 pull request #27
Opened 2022-09-01 18:42 UTC by krzysiekn111

2022-09-01 20:45 UTC, Merior94 requested changes
Nie znalazłem też metody usuwającej produkty z koszyka

2022-09-01 20:45 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        return ResponseEntity.ok().build();
Tu można wynik z metody cart wrzucić jako wynik do response. Zawsze to jakaś sensowniejsza odpowiedź od serwera niż samo OK

2022-09-01 20:45 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        return ResponseEntity.ok().build();
Tu podobnie jak wyżej, zwróciłbym koszyk

2022-09-01 20:45 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +                .orElseThrow(Exception::new);
Tu exception może być bardziej szczegółowy, tak jak np. Cart does not exits czy coś takiego

2022-09-01 20:45 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +                .orElseThrow(Exception::new);
I to dodać do GlobalHttpErrorHandler tak jak przy innych wyjątkach

2022-09-01 20:45 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        return ResponseEntity.ok().build();
wgl. całą implementację przeniósłbym do cartService a tu zostawić tylko wywołanie odpowiedniej metody

2022-09-01 23:44 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                                   @RequestBody long productId) throws Exception {
Exception można zamienić na coś co będzie bardziej informowało o konkretnym błedzie, np. możesz wykorzystać CartNotFoundException lub ProductNotFoundException które już istnieją w projekcie.

2022-09-01 23:48 UTC, arekgorka commented
+ nie buduje się i jest dużo konfliktów. Jak możesz to sprawdź czy masz najnowsze zmiany u siebie w projekcie :) Część problemów powinna się wyjaśnić.

2022-09-01 23:51 UTC, arekgorka requested changes
nie buduje się i jest dużo konfliktów. Jak możesz to sprawdź czy masz najnowsze zmiany u siebie w projekcie :) Część problemów powinna się wyjaśnić.

2022-09-02 11:59 UTC, piotr-kostka commented
Projekt dalej się nie buduje i jest mnóstwo konfliktów. Zacznij od zmergowania maina do tego brancha, żeby usunąć konflikty a potem dopiero zmieniaj implementację CartControllera

2022-09-02 12:03 UTC, piotr-kostka requested changes
Projekt dalej się nie buduje i jest mnóstwo konfliktów. Zacznij od zmergowania maina do tego brancha, żeby usunąć konflikty a potem dopiero zmieniaj implementację CartControllera

2022-09-02 20:38 UTC, piotr-kostka commented
wyskakują jeszcze jakieś 2 konflikty

2022-09-03 09:24 UTC, piotr-kostka commented
Naprawiłem konflikty i usunąłem zdublowane klasy

2022-09-03 10:15 UTC, Merior94 commented
> Naprawiłem konflikty i usunąłem zdublowane klasy

Potwierdzam że projekt się buduje

2022-09-03 10:26 UTC, Merior94 approved these changes

2022-09-03 10:28 UTC, Merior94 commented
`    public void deleteCart(final long id) {
        cartRepository.deleteById(id);
    }`
Czepiając się, zmieniłbym albo nazwę metody na deleteCartById albo przyjmowany typ na obiekt Cart

2022-09-06 19:05 UTC, piotr-kostka commented
potrzebna poprawa metody getCarts() i addProduct()

2022-09-06 21:25 UTC, arekgorka reviewed
@piotr-kostka Generalnie mi się podoba :) Przeniósłbym tylko logikę z controllerów @PutMapping 'getProductIntoCart oraz  @PostMapping 'createCart" do Service. 
Tak dla porządku ;)

2022-09-06 21:25 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public ResponseEntity<CartDto> putProductIntoCart(@PathVariable long cartId, @RequestBody Product product)
wydaje mi się że powinien być ProductDto. Żeby klasa Product nie była ani klasą wchodzącą ani wychodzącą z aplikacji. :)

2022-09-07 08:13 UTC, piotr-kostka commented
Implementacja przeniesiona do JDP220902-23b (https://github.com/piotr-grosicki/project-jdp-2209-02/tree/JDP220902-23b)

2022-09-08 10:20 UTC, closed without merging