JDP220902-38 Zmiany w UserDbService
piotr-grosicki/project-jdp-2209-02 pull request #44
Opened 2022-09-10 18:04 UTC by Merior94

Sprawdzałem w postmanie. Działa poprawnie.
W razie podania błędnego id dostajemy błąd nieistniejącego usera.
Jeśli id się zgadza ale login się nie zgadza, dostajemy błąd logowania.
Nowy kod generowany jest tylko jeśli stary wygasł. Jeśli stary wciąż jest aktywny, nowy nie jest generowany i dostajemy zwrotkę z tym starym, wciąż aktualnym.

2022-09-11 20:47 UTC, arekgorka requested changes
Stworzyłeś UserLoginFailedException, ale nie widzę żebyś z tego gdzieś korzystał w kodzie. 
Trzeba to albo usunąć albo użyć tak gdzie pierwotnie myślałeś :D

2022-09-11 20:47 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public ResponseEntity<UUID> createUserKey2(@RequestBody UserDto userDto) throws UserNotFoundException {
tu pewnie trzeba usunąć "2" z createUserKey2 ;)

2022-09-11 21:22 UTC, arekgorka commented
plus trzeba rozwiązać konflikt

2022-09-12 15:21 UTC, piotr-kostka approved these changes
Poprawiłem konflikt plus zmiany wg review - wszystko działa w postmanie

2022-09-12 16:38 UTC, arekgorka approved these changes

2022-09-12 16:38 UTC, merged