JDP220902-4
piotr-grosicki/project-jdp-2209-02 pull request #5
Opened 2022-08-22 17:10 UTC by ptynek

2022-08-22 17:42 UTC, s20308-pj approved these changes

2022-08-22 18:25 UTC, piotr-grosicki requested changes
te dto juz istnieja w repozytorium na branchy main

2022-08-22 18:43 UTC, ptynek commented
> te dto juz istnieja w repozytorium na branchy main

pliki usunięte. Zostawione tylko OrderDto i OrderController

2022-08-22 19:51 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
> +    private CartDto cartDto;
tu bym zostawił tak jak było wcześniej - long userId i cartId

2022-08-22 20:53 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
>      private BigDecimal totalPrice;
nie wiem czy potrzebujemy aż tak gigantycznych liczb zmiennoprzecinkowych. Jak dla mnie zwykłe double wystarcza.

2022-08-22 21:14 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
>      private BigDecimal totalPrice;
Też się nad tym zastanawiałem ;) dla bardzo szczegółowych wyliczeń BigDecimal byłby dobry ale w zwykłym sklepie chyba takich obliczeń nie ma

2022-08-23 02:05 UTC, ptynek commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
>      private BigDecimal totalPrice;
@arekgorka @piotr-kostka BigDecimal nie jest zastosowany ze względu na zakres liczb, a na dokładność. Teraz może wydawać się to głupie, ale za tydzień robiąc jakiś test i dodając 10,40 do 10,42 wynik może wyjść 20,83, ponieważ double nie jest na tyle dokładne z tego co pamiętam, żeby używać je do obliczania dokładnych rzeczy, jakimi są np. kwoty za jakieś usługi bądź towary.

2022-08-23 05:44 UTC, merged