JDP220902-12
piotr-grosicki/project-jdp-2209-02 pull request #8
Opened 2022-08-23 17:18 UTC by piotr-kostka

2022-08-23 17:20 UTC, piotr-kostka commented
Wykonane na podstawie cherry-pick JDP220902-13

2022-08-23 21:18 UTC, arekgorka approved these changes

2022-08-24 06:10 UTC, piotr-grosicki requested changes
konflikty

2022-08-24 10:33 UTC, piotr-kostka commented
Po pracy się tym zajmę

2022-08-25 06:47 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2022-08-25 14:35 UTC, arekgorka approved these changes

2022-08-25 17:51 UTC, ptynek approved these changes

2022-08-25 17:55 UTC, ptynek commented
Podczas tworzenia testu działało u mnie poprawnie. Można jeszcze się pokusić o commit z konstruktorem.

2022-08-26 06:18 UTC, merged