Jdp220902 15
piotr-grosicki/project-jdp-2209-02 pull request #9
Opened 2022-08-24 09:09 UTC by s20308-pj

2022-08-24 10:02 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private boolean isBlocked;
W zadaniu jest jeszcze mowa u tworzeniu userKey więc też bym od razu dodał taką kolumnę

2022-08-24 10:03 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Entity(name = "USER")
wszystkie encje mamy w liczbie mnogiej to tu też by mogło być "USERS"

2022-08-24 10:09 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private boolean isBlocked;
Przydałoby się jeszcze połączenie oneToOne z encją Order

2022-08-24 11:10 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private boolean isBlocked;
opierałem się na stworzonym diagramie - coś zmienialiście?
userKey - jaki ma być typ danych?

2022-08-24 11:18 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private boolean isBlocked;
w diagramie tego nie ma ale jest w treści modułu 25.4 - lista endpointów -> users - trzecia kropka. Moim zdaniem typ int

2022-08-24 11:33 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String login;
ja bym jeszcze dorzucił @NotNull przy plach 'login', 'mail', 'adress' i 'isBlocked' :)

2022-08-24 11:33 UTC, arekgorka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private String login;
zakładam że te dane są potrzebne do wysyłki (w prawdziwym sklepie) więc nie mogą być nullami.

2022-08-24 11:38 UTC, piotr-kostka commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
Połączenie jest już w encji Cart, więc zdublowane jest

2022-08-24 13:50 UTC, s20308-pj commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private boolean isBlocked;
dodaję też czas ostatniego logowania

2022-08-25 06:47 UTC, piotr-grosicki requested changes
konflikty

2022-08-25 19:59 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +            fetch = FetchType.LAZY
Czy opcja LAZY jest konieczna? Nie bardzo jeszcze chyba rozumiem, ale przy testach tej encji wyrzuca mi tu błędy dopóki nie zmienię na EAGER

2022-08-26 06:18 UTC, merged

2022-08-30 17:40 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      @NotNull
@NotNull przy polu id imho do usunięcia

2022-08-30 17:41 UTC, Merior94 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      @NotNull
```suggestion

```